# Azure Pipeline YAML

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
    
- script: |
    tree .
  displayName: 'Display Directory Tree'


- script: |
    sudo apt install -y docker-compose
  displayName: 'install docker-compose'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'EdgeAPIRegistry'  # Change this to your Docker registry endpoint
    dockerComposeFile: 'docker-compose.yaml'
    dockerComposeCommand: 'up -d'
    action: 'Run a Docker Compose command'

- script: |
    mkdir -p artifacts
  displayName: 'Create Artifacts Directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifacts'  # Path to your artifacts directory
    ArtifactName: 'output-files'
