trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
    
- script: |
    tree .
  displayName: 'Display Directory Tree'

- script: |
    docker build -t get-data-image Get_Edge_Data
    docker run --name get-data get-data-image
    # Check for errors
    if [ $? -ne 0 ]; then
      echo "Error: Docker build or run failed."
      exit 1
    fi
  displayName: 'Build and Run Docker Image'

- script: |
    mkdir -p artifacts
  displayName: 'Create Artifacts Directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifacts'
    ArtifactName: 'get-data-output'
