version: "3.8"

services:

  mongodb:
    build:
      context: ./mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  fastapi:
    build:
      context: ./Edge_Data_API
    ports:
      - "8000:8000"
    depends_on:
      - data_collection

  data_collection:
    build:
      context: ./Get_Edge_Data
    depends_on:
      - mongodb

volumes:
  mongodb_data: # Named volume for MongoDB data
